### ISSUE TITLE
Nested ssh session possible?

### ISSUE THREAD

**Issue by cassanof** [openssh-rust/openssh#105]
Hi, I was wondering if keeping a nested (doubly) ssh session was possible using this crate.
I need to do the following thing:

connect to server 1
from server 1, connect to many other servers, that are reachable only from server 1

I cannot do SSH tunnel with my setup.

Thanks.

**Comment by NobodyXu** [comment]
Perhaps you can use [ssh jumphost](https://wiki.gentoo.org/wiki/SSH_jump_host)?
[`openssh::SessionBuilder::jump_hosts`] can be used to configure jump hosts which might solve your problem.

[`openssh::SessionBuilder::jump_hosts`]: https://docs.rs/openssh/latest/openssh/struct.SessionBuilder.html#method.jump_hosts

**Comment by NobodyXu** [comment]
Or, you can first connect to server 1, manually execute `ssh` command on it which connections to server 2.

**Comment by cassanof** [comment]
`jump_hosts` worked perfectly, thanks!
