### ISSUE TITLE
SSH_AUTH_SOCK environment variable should be passed to SSH

### ISSUE THREAD

**Issue by TaaviE** [openssh-rust/openssh#108]
Right now it seems that `openssh::Session::connect_mux` does not pass `SSH_AUTH_SOCK` environment variable to the child SSH process, breaking all setups that depend on an SSH agent.

This is exhibited by getting a PermissionDenied error when trying to establish a connection ` Connect(Custom { kind: PermissionDenied, error: "pin required\r\nuser@example.com: Permission denied (publickey)." })'` while the same host does not prompt for anything when using `ssh` standalone.

**Comment by NobodyXu** [comment]
I can add a new option to the builder for this so that `SSH_AUTH_SOCK` get passed by default.

**Comment by Avamander** [comment]
I think that would be great.

**Comment by TaaviE** [comment]
I think that would be great.

**Comment by NobodyXu** [comment]
@TaaviE Released in 0.9.9
