### ISSUE TITLE
Make Session function public for external calls

### ISSUE THREAD

**Issue by baoyachi** [openssh-rust/openssh#124]
Currently, I have implemented a Session object myself. Can these two methods be opened for external self control calls.

Make `new_process_mux` or `new_native_mux` public .

```diff

mpl Session {
    #[cfg(feature = "process-mux")]
+    pub(super) fn new_process_mux(tempdir: TempDir) -> Self {
        Self(SessionImp::ProcessImpl(process_impl::Session::new(tempdir)))
    }

    #[cfg(feature = "native-mux")]
+    pub(super) fn new_native_mux(tempdir: TempDir) -> Self {
        Self(SessionImp::NativeMuxImpl(native_mux_impl::Session::new(
            tempdir,
        )))
    }
}
```

[About code link ref:](https://github.com/openssh-rust/openssh/blob/3319a8162a/src/session.rs#L56-L65)

**Comment by NobodyXu** [comment]
You can use Session::{resume, resume_mux}, which might be enough for your use case.

**Comment by NobodyXu** [comment]
If it's not enough, then we can make them public

**Comment by baoyachi** [comment]
@NobodyXu 
Because the internal implementation of the resume method is to set `TempDir` to None, but currently, I need external control to pass this tempdir to Sesson internally.

[ native_mux_impl link ref](https://github.com/openssh-rust/openssh/blob/master/src/native_mux_impl/session.rs#L27-L29)
[process_impl](https://github.com/openssh-rust/openssh/blob/master/src/process_impl/session.rs#L32-L38)

So, I really hope these two methods are publicly available.

**Comment by NobodyXu** [comment]
@baoyachi I will accept a PR for this with enough documentation on how to use it.

**Comment by baoyachi** [comment]
I will send PR later to solve this issue too.
