### ISSUE TITLE
Is it possible to clean up the historical control_directory before creating a SessionBuilder?

### ISSUE THREAD

**Issue by baoyachi** [openssh-rust/openssh#125]
Currently testing locally, the historical [control_directory](https://docs.rs/openssh/latest/openssh/struct.SessionBuilder.html#method.control_directory) directory will always exist during each debugging session.

E.g:
```shell
➜ ll -als
total 0
0 drwxr-xr-x  6 root  staff   192B  7 28 10:03 .
0 drwxr-xr-x  3 root  staff    96B  7 27 18:25 ..
0 drwxr-xr-x  4 root  staff   128B  7 28 09:55 .ssh-connectionpCn9J7
0 drwxr-xr-x  2 root  staff    64B  7 28 10:01 .ssh-connectionpHq9a2
0 drwxr-xr-x  2 root  staff    64B  7 28 10:03 .ssh-connectionpJp983
0 drwxr-xr-x  2 root  staff    64B  7 28 10:05 .ssh-connectionpLwp24
```

**Comment by NobodyXu** [comment]
[`run_ci_tests.sh`](https://github.com/openssh-rust/openssh/blob/master/run_ci_tests.sh) take care of that to remove these control-dirs.

**Comment by baoyachi** [comment]
Oh. Could we add a method in the code similar to *clean_control_directory*?
With this method, I can control the file directory cached by control_directory before the code execution. If needed, I can submit a pull request .

**Comment by NobodyXu** [comment]
> Oh. Could we add a method in the code similar to _clean_control_directory_?

Hmmm, I don't think such code belong to `openssh` though.
