### ISSUE TITLE
Blocking wrapper

### ISSUE THREAD

**Issue by Ten0** [openssh-rust/openssh#14]
It would be useful to have a blocking wrapper around this library, for use in blocking code.
It could be built in a similar fashion as that of [`reqwest`](https://docs.rs/reqwest/0.10.7/reqwest/blocking/index.html). It could be a feature, or an external crate.

**Comment by jonhoo** [comment]
I don't personally have a need for that, and am fairly busy these days, but if you have some spare cycles and want to give it a try, I'd be happy to look at a PR! Alternatively, it may be that the best way to go about this is to simply write a separate blocking wrapper crate around `openssh` :)

**Comment by NobodyXu** [comment]
@Ten0 Do you still need a blocking version of this crate?

I could implement one as an external crate if you still need it

**Comment by Ten0** [comment]
I imagined using this for sftp but it seems that is now a separate crate - which we haven't had time to try migrating to yet unfortunately, so I can't say for sure :/

If that crate fits our needs, we would benefit from a sync interface on there, but would need more time to test it. :/

**Comment by NobodyXu** [comment]
Sure, feel free to open new issues or open/review PRs on [`openssh-sftp-client`](https://github.com/openssh-rust/openssh-sftp-client).
