### ISSUE TITLE
Bug/Test failure on MacBook

### ISSUE THREAD

**Issue by NobodyXu** [openssh-rust/openssh#63]
On Macbook Air 2020 with MacOS `12.3.1`, I got the following error when running `check.sh` and `run_ci_tests.sh`:

```
failures:

---- no_route stdout ----
Custom { kind: ConnectionAborted, error: "connect to host 255.255.255.255 port 22: Address family not supp
orted by protocol family" }
thread 'no_route' panicked at 'assertion failed: `(left == right)`
  left: `ConnectionAborted`,
 right: `Other`', tests/openssh.rs:676:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    no_route
```

The test in question is [`no_route`](https://github.com/openssh-rust/openssh/blob/729fe31bc184e5d352a752d79b4233bfbf872c17/tests/openssh.rs#L676).

The error is created using [`Error::interpret_ssh_error`](https://github.com/openssh-rust/openssh/blob/729fe31bc184e5d352a752d79b4233bfbf872c17/src/error.rs#L152).

**Comment by jonhoo** [comment]
Huh, interesting. This seems like it's just a difference of opinion among OSes on how a given error kind should be surfaced. I'm not _too_ fussy about exactly which kind we raise for something like `255.255.255.255`, but we could perhaps update the test to use a different non-routable address that the OSes agree on the error for.

**Comment by NobodyXu** [comment]
> Huh, interesting. This seems like it's just a difference of opinion among OSes on how a given error kind should be surfaced. I'm not _too_ fussy about exactly which kind we raise for something like `255.255.255.255`, but we could perhaps update the test to use a different non-routable address that the OSes agree on the error for.

Not sure how to find that IP that is portable between Linux and MacOS.

Maybe we should just relax on the error kind.

**Comment by NobodyXu** [comment]
Considering #42 , I would say running all the tests in the container is the best solution, but I want the compilation of tests to be run directly, otherwise it would be hard to cache `target` and `ci-target` and it would make compilation slower on MacOS since docker-on-mac is run inside a vm.

**Comment by jonhoo** [comment]
I think 192.0.2.1 [should work](https://datatracker.ietf.org/doc/html/rfc5737). 169.254.255.254 also [seems pretty safe](https://datatracker.ietf.org/doc/html/rfc3927).

**Comment by NobodyXu** [comment]
> I think 192.0.2.1 [should work](https://datatracker.ietf.org/doc/html/rfc5737). 169.254.255.254 also [seems pretty safe](https://datatracker.ietf.org/doc/html/rfc3927).

Use of these two IP addresses seem to cause `no_route` to stuck forever

**Comment by jonhoo** [comment]
That's very weird. It certainly shouldn't get _stuck_. Does that happen on Linux too?

**Comment by NobodyXu** [comment]
> That's very weird. It certainly shouldn't get _stuck_. Does that happen on Linux too?

Yes, both of them stuck on Linux, too.

**Comment by jonhoo** [comment]
I wonder if the trick here is going to be to set the connection timeout for the TCP connection. That way, it shouldn't hang indefinitely but rather error out after the timeout expires. And we can set that timeout pretty short here.
