### ISSUE TITLE
Can I use -J flag to do jumphosts?

### ISSUE THREAD

**Issue by Niedzwiedzw** [openssh-rust/openssh#84]
I have a central server that is authenticated with multiple machines and I need to use it as an intermediate jump host. Is this option exposed by any chance?

**Comment by NobodyXu** [comment]
It currently isn't exposed, but a PR for that is always welcomed.

As a workaround, you can use [SessionBuilder::config_file](https://docs.rs/openssh/latest/openssh/struct.SessionBuilder.html#method.config_file) to specify an alternative config file which has the jumphost configuration.

**Comment by NobodyXu** [comment]
@Niedzwiedzw Your feature request is now implemented in #91
