### ISSUE TITLE
Username and password authetication

### ISSUE THREAD

**Issue by jmmb13** [openssh-rust/openssh#96]
Hi,

I saw the issue #68, and from documentation, it is not possible to use username and password for the session, only key-pairs. Would it be possible to add this authentication as this [ssh2 crate](https://docs.rs/ssh2/0.3.1/ssh2/#authenticating-with-a-password) did?

Thank you for your attention!
jmmb

**Comment by jonhoo** [comment]
No, this crate will not implement password-based authentication. It's asking for trouble, especially in a crate that will generally be used for automation :)
