### ISSUE TITLE
Piping between std::process::Command stdout and openssh::session::RemoteChild

### ISSUE THREAD

**Issue by TaaviE** [openssh-rust/openssh#97]
I tried following the example provided by `std::process::Stdio::piped()` unfortunately doesn't work because of the following:
```
the trait bound `openssh::Stdio: From<tokio::process::ChildStdout>` is not satisfied E0277 the trait `From<tokio::process::ChildStdout>` is not implemented for `openssh::Stdio` Help: the following other types implement trait `From<T>`:
```

Short example snippet:
```rust
async fn ... {
    ....

    let source = Command::new("util1")
        .stdout(Stdio::piped())
        .spawn()
        .unwrap()
        .stdout
        .unwrap();

    let destination = remote.command("util2")
        .stdin(source) // Incorrect
        .spawn()
        .await
        .unwrap();

    // TODO: Alterative?
}
```

What would be the correct/best way to pipe local process' stdout into remote process' stdin with this crate? Sorry if this question is too basic, I can't wrestle the compiler that well yet :)

**Comment by NobodyXu** [comment]
Change the second part to this:

```rust
    let destination = remote.command("util2")
        .stdin(source.into())
        .spawn()
        .await
        .unwrap();
```

Note that even if you are not using `openssh` but `std::process` or `tokio::process`, you would still need this `.into()`.

`stdin`/`stdout`/`stderr` method takes a `Stdio` (`openssh` has its own `Stdio` type though) but `stdout.unwrap()` gives you `std::process::ChildStdout`.

`Stdio` can be constructed `from` `ChildStdout`, but you cannot directly pass it to `stdin`.

**Comment by TaaviE** [comment]
Unfortunately `source.into()` did not work because of `^^^^ cannot infer type for type parameter 'T' declared on the trait 'Into'`

It did give me an idea and I ended up with this, thanks!
```
    let mut source = Command::new("util1")
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();

    let destination = remote.command("util2")
        .stdin(source.stdout.take().unwrap())
        .spawn()
        .await
        .unwrap()
        .wait_with_output()
        .await
        .unwrap();
```

Though it's really rather ugly, but seems to work.

**Comment by NobodyXu** [comment]
Oh right I forgot that `Command::stdin` takes anything `Into<Stdio>`, so the really reason you code didn't work is because `stdout.unwrap()` is a reference, while `Stdio::from` takes `ChildStdout` by value.
